name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ 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 }}
          GIST_ID: ${{ b881e445ef91ba4c43473f6b340a8631 }}
          TIMEZONE: Asia/Seoul
